version: '3.8'

services:
  database:
    container_name: database
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: personal
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    ports:
      - '4306:3306'
    volumes:
      - ./mysql:/var/lib/mysql
  php:
    container_name: php
    build:
      context: docker/php
    ports:
      - '9000:9000'
      #- '9051:9050'
    volumes:
      - ./app:/var/www/personal
    depends_on:
      - database
    environment:
      PHP_IDE_CONFIG: 'serverName=0.0.0.0'

  nginx:
    container_name: nginx
    image: nginx:stable-alpine
    ports:
      - '8080:80'
    volumes:
      - ./app:/var/www/personal
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - database
  pma:
    image: phpmyadmin:5.1
    restart: always
    links:
      - database
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: database
      PMA_USER: symfony
      PMA_PASSWORD: symfony
      PMA_PORT: 3306
    ports:
      - '8888:80'